import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers";
import { Poppins } from "next/font/google";

export const poppins = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.className} antialiased  bg-white dark:bg-[#050709]`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
